### PR TITLE
Sortable fix

### PR DESCRIPTION
**Pull request by mnoack**

### CODE REVIEW

**Comment by msmirnoff** [comment]
@mnoack 
Please satisfy The Hound ? :dog:

**Comment by mnoack** [comment]
@msmirnoff I politely disagree with the hound - @adz / @AlessandroBerardi

**Comment by msmirnoff** [comment]
@mnoack 
Ok. I do have to agree with you, the Hound review isn't hugely useful here.
I'll review as is. I just feel pangs of pain and regret about this... just would prefer not getting Hound's feedback at all if we are going to just ignore it anyway. :cry:

**Comment by msmirnoff** [comment]
:+1:

**Pull request merged**
